### ISSUE TITLE
Import hooks doesn't work?

### ISSUE THREAD

**Issue by sergunich** [benjamn/reify#61]
I'm trying to execute local file, but it doesn't work and I can't understand why.

Steps to reproduce:
```
user@host:/# docker run -it node:6.9.4-slim bash
user@container:/# npm install reify@0.4.7
user@container:/# echo 'import acorn from "acorn"' > foo.js
user@container:/# nodejs --require 'reify' ./foo.js
(function (exports, require, module, __filename, __dirname) { import acorn from acorn
                                                              ^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Module.Mp._compile (/node_modules/reify/node/compile-hook.js:10:21)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at Module.Mp.load (/node_modules/reify/node/runtime.js:16:23)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
```

I'm doing some obvious mistake?

**Comment by benjamn** [comment]
You need a `package.json` file and then `npm install --save reify`.

The compiler is only enabled for packages that explicitly depend on `reify`, so that it can avoid compiling every file used by Node.

**Comment by benjamn** [comment]
This is definitely something the compiler should warn about, since it's able to catch the exception for files it wasn't planning to compile.

**Comment by jdalton** [comment]
Since the compiler is only enabled for files that opt in, those that don't will hit the traditional Node import which is outside the reach of reify.
